export const LOGIN = 'login';
export const ADD_CURRENCIES = 'add currencies';
export const ADD_EXPENSE = 'add expense';
export const ADD_NAME_CURRENCIES = 'add currencies names';
export const REMOVE_EXPENSE = 'remove expense';
export const EDIT_EXPENSE = 'edit expense';
export const ENABLE_EDITOR = 'enable editor';
export const DISABLE_EDITOR = 'disable editor';
export const SAVE_ID_EDIT = 'save id to edit item in array';
