import PropTypes from 'prop-types';

export const nameCurrencyValidator = PropTypes.shape({
  USD: PropTypes.string,
  CAD: PropTypes.string,
  EUR: PropTypes.string,
  GBP: PropTypes.string,
  ARS: PropTypes.string,
  BTC: PropTypes.string,
  LTC: PropTypes.string,
  JPY: PropTypes.string,
  CHF: PropTypes.string,
  AUD: PropTypes.string,
  CNY: PropTypes.string,
  ILS: PropTypes.string,
  ETH: PropTypes.string,
  XRP: PropTypes.string,
});
export const expensesValidator = PropTypes.shape({
  USD: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  USDT: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  CAD: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  EUR: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  GBP: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  ARS: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  BTC: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  LTC: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  JPY: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  CHF: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  AUD: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  CNY: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  ILS: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  ETH: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  XRP: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
  DOGE: {
    code: PropTypes.string,
    codein: PropTypes.string,
    name: PropTypes.string,
    high: PropTypes.string,
    low: PropTypes.string,
    varBid: PropTypes.string,
    pctChange: PropTypes.string,
    bid: PropTypes.string,
    ask: PropTypes.string,
    timestamp: PropTypes.string,
    create_date: PropTypes.string,
  },
});
